### ISSUE TITLE
White links are invisible with white background

### ISSUE THREAD

**Issue by minkkinen** [lifegems/obsidian-related-notes-finder#2]
In style.css, the ```.possible-link-item``` is given a white color. This makes it impossible to see with a white background. I removed that line and now the links show up fine. Could this color line be either removed from style.css or made to respect dark or light mode?

**Comment by lifegems** [comment]
@minkkinen Thanks for the tip.

Please update to v1.1.0 to use the updated styling.

Ref: https://github.com/lifegems/obsidian-related-notes-finder/releases/tag/1.1.0
