### ISSUE TITLE
Plugin manifest error

### ISSUE THREAD

**Issue by lishid** [lifegems/obsidian-related-notes-finder#3]
Hey, seems like you forgot to update your plugin manifest's author field:
https://github.com/lifegems/obsidian-related-notes-finder/blob/6e1d0d51f2980914c93d8ecf6616ec5cf4e7417e/manifest.json#L7

Please have it updated soon, thanks!

**Comment by lifegems** [comment]
Fixed @lishid. Thank you

Ref: https://github.com/lifegems/obsidian-related-notes-finder/tree/1.0.7
